const Replicate = require("replicate");
require("dotenv").config();

// Oslo — Free Framer Creative Portfolio
const text = [
  "We specialize in crafting exceptional digital experiences to help our clients achieve their business goals.",
  "Product Design Experience",
  "Scroll to explore",
  "We strive to bring innovation and creativity to every project we undertake. Our team of experts works closely with our clients to understand their needs and deliver outstanding solutions. We are dedicated to creating products that exceed our clients' expectations.",
  "Example Project Header",
  "Click",
  "Work",
  "EXPLORE",
  "Framer template crafted with love by Dawid Pietrasiak",
  "We don't just create brands; we craft unforgettable experiences that leave a lasting impression.",
  "Studio",
  "We pride ourselves on partnering with founders to turn their ambitious visions into transformative brands. Since 2013, we have been creating designs that not only stand out but also deliver results.",
  "Our portfolio speaks for itself. With over 70 awards in design and digital innovation, we have a proven track record of delivering recognition and success for our partners. Our team of experts is dedicated to understanding your business needs and creating designs that align with your goals. Let us help you elevate your brand and stand out in your industry.",
  "Research & Brand Strategy",
  "Brand StrategyResearch & Insights• Content Marketing• User Experience Research",
  "Creative Direction & Design",
  "Web DesignUX & UI DesignBrand Identity• Interaction DesignVideo Production• Animation• Illustration",
  "We believe that it is possible to live in a world where every product or service is designed with an easy-to-use experience in mind",
  "Let's talk",
  "Connecting with our clients to create tailor-made solutions",
  "New York2210 18th Street,New York, NY 80024Rome4020 20th Street,3920 Rome",
  "LinkHere",
  "hello@framer.com",
  "Oops. It looks like the page you're trying to reach doesn't exist or has been moved.",
  "Suitcase App",
  "Travel Smart & Safely",
  "Ziggo is designed to provide travelers with peace of mind and enhanced security by offering a range of smart features that make managing luggage simpler and more efficient.",
  "Client",
  "TravelTech Innovations",
  "Services",
  "Visual DesignUI & UX Design",
  "Industries",
  "Travel",
  "Date",
  "January 2023",
  "Top Project Description",
  "Bottom Project Description",
  "Visual Design\nUI & UX Design",
  "The primary objective was to create an intuitive and reliable app that integrates seamlessly with smart suitcases, offering functionalities such as remote locking and unlocking, battery level monitoring, and real-time notifications if the suitcase moves beyond a certain distance from the user. The project aimed to enhance the travel experience by providing users with ultimate control and security over their luggage, reducing stress and improving convenience during journeys.\n\n The development of the Ziggo app has had a significant impact on the travel experience for users, offering enhanced security, convenience, and peace of mind. The ability to remotely control and monitor their luggage has reduced the stress associated with traveling, particularly in busy and unfamiliar environments. ",
  "Overall, the Ziggo app has successfully enhanced TravelTech Innovations' product offering, positioning the company as a leader in smart travel technology. The app has received excellent reviews from users, highlighting its reliability, ease of use, and the added security it provides. As a result, TravelTech Innovations has seen increased customer loyalty and a growing user base, solidifying its reputation in the market.",
  "Exchango Dashboard",
  "Real-Time Currency Tracking and Analysis",
  "GlobalFinance Inc. approached us to develop an intuitive and comprehensive currency exchange dashboard app. The primary objective was to offer a seamless user experience, providing real-time exchange rate information, historical trends, and predictive analytics.",
  "GlobalFinance Inc.",
  "The development of the currency exchange dashboard app significantly enhanced GlobalFinance Inc.'s service offerings. Users experienced a seamless and efficient way to manage their international finances. The real-time data, combined with powerful analytics and a user-friendly interface, empowered users to make well-informed financial decisions. ",
  "Feedback from users highlighted the app’s ease of use, reliability, and the valuable insights it provided, cementing GlobalFinance Inc.'s position as a leader in international financial services.",
  "Copay",
  "Simple Banking Rewarding System",
  "Unlock the future of seamless banking with Copay, where user experience meets unparalleled rewards. Our cutting-edge UX/UI digital project redefines the banking landscape, making every interaction effortless and every transaction rewarding.",
  "Copay Bank",
  "Banking",
  "The journey began with a vision: to create a banking platform that prioritized simplicity without compromising functionality. The UX/UI design team meticulously crafted an interface that seamlessly guided users through their financial activities. From account management to transaction histories, every feature was intuitively designed for effortless navigation.",
  "The results were staggering. Copay not only achieved its goal of simplifying banking but exceeded expectations in every aspect. User satisfaction soared as customers reveled in the seamless experience and lucrative rewards. The platform's user base grew exponentially, cementing Copay's position as a leader in the digital banking space.",
  "Paws & Plans App",
  "The Ultimate Veterinary Clinic Scheduler",
  'Say goodbye to missed appointments and scheduling headaches. With "Paws & Plans," PetCare Plus Veterinary Clinic is revolutionizing the way pet owners manage their furry friends\' healthcare. ',
  "PetCare Plus Clinic",
  "Healthcare",
  '"Paws & Plans" offers a comprehensive suite of features to streamline every aspect of your pet\'s healthcare journey. With an intuitive calendar system, scheduling veterinary appointments has never been easier. Additionally, the app provides medication reminders, ensuring your furry friend stays on track with their treatment plan. Accessing your pet\'s medical records is a breeze with "Paws & Plans," allowing for seamless communication with your veterinarian and ensuring continuity of care. ',
  "In summary, \"Paws & Plans\" is more than just a mobile app – it's a game-changer in pet care management. By simplifying scheduling, providing medication reminders, and granting access to medical records, the app empowers pet owners to take control of their pet's health with ease and confidence. ",
  "Vet Clinic App",
  "Copay System",
];

// Pepper — Restaurant/Food Delivery Template
const text3 = [
  "Your Pizza PartyStarts Here!",
  "Gather your friends and family and enjoy the best pizza in town. Freshly made and delivered hot!",
  "Fan Favorites",
  "From classic combinations to bold flavors, these pizzas top our list for a reason.",
  "Hot Pizza, Hotter Deals",
  "From family-sized deals to solo slices, find the perfect offer for your pizza cravings.",
  "Save Room for Dessert!",
  "Our desserts are worth it. Trust us, you won’t want to miss these sweet delights.",
  "Find Your Nearest Pizza Spot",
  "Locate our stores, check delivery zones, and pick the best option for you!",
  "Our Menu",
  "From savory pizzas to refreshing drinks, we take pride in serving dishes that are made with care. Every meal is thoughtfully prepared to give you a culinary experience worth remembering.",
  "Contact Us",
  "Whether you have a question, feedback, or just want to say hi, we're always here for you. Reach out and let us know how we can make your experience even better.",
  "Addresses",
  "Write Us a Message",
  "Maps & Delivery Info",
  "404",
  "OOPS!!The page you are looking for wasn't found!",
  "Pizza",
  "Pepper",
  "Button",
  "Title",
  "Price - Large",
  "Alergen Warnings",
  "Ingredients",
  "Date",
  "Category",
  "Price - Medium",
  "Spicy Duo Deal",
  "1 Medium Firecracker Inferno 1 Medium Buffalo Bliss",
  "Cheese Lovers Pair",
  "1 Medium Cheese Avalanche1 Medium Truffle Temptation",
  "Veggie Delight Duo",
  "1 Medium Mediterranean Marvel1 Medium Garlic Supreme",
  "Sweet & Savory Combo",
  "1 Medium Hawaiian Heatwave1 Medium Pepperoni Popper",
  "Meat Feast Combo",
  "1 Medium Meat Lover's Feast1 Medium BBQ Blaze",
  "New York",
  "View map",
  "Delivery Zones",
  "New York:We deliver within a 10-mile radius of our central location in Manhattan.Zip Codes Covered: 10001, 10002, 10003, 10011, 10019, and nearby.",
  "Amsterdam:We deliver across the Amsterdam-Centrum and neighboring districts, within a 7 km radius.Postcodes Covered: 1011-1019, 1050, and nearby.",
  "Bucharest:Delivery covers a 10 km radius from our central Piata Romana location.Postcodes Covered: 010011-010999, 030011-030999, and nearby.",
  "London:Our delivery services cover areas within a 10 km radius from our location in Soho.Postcodes Covered: W1, SW1, WC1, NW1, and nearby.",
  "Berlin:We deliver within a 10 km radius of our Mitte location.Postcodes Covered: 10115, 10435, 10997, and nearby.",
  "Delivery Methods:Online Ordering: Place your order directly on our website for quick and easy delivery.Phone Orders: Call our store to place your delivery order.Partner Apps: Available on Uber Eats, DoorDash (New York, London, Berlin), and Glovo (Bucharest, Amsterdam).",
  "Delivery Fees & Minimum Order:New York: $2.99 delivery fee | $15 minimum orderLondon: £3.50 delivery fee | £12 minimum orderAmsterdam: €2.50 delivery fee | €15 minimum orderBerlin: €2.99 delivery fee | €12 minimum orderBucharest: 12 RON delivery fee | 50 RON minimum order",
  "Delivery Time Estimate:We aim to deliver within 30-45 minutes in all cities. Times may vary based on traffic, weather, and peak hours.",
  "Contactless Delivery:Contactless delivery is available upon request for all orders. Simply select the option during checkout for a no-contact drop-off.",
  "New York:Pickup is available at our Manhattan location. Place your order online or call ahead for fast pickup service.",
  "London:Swing by our Soho location for pickup. Order online in advance to skip the wait.",
  "Amsterdam:Convenient pickup at our Amsterdam-Centrum store. Pre-order online for quick collection.",
  "Berlin:Pickup is available at our Mitte location. Skip the queue by placing your order online for collection.",
  "Bucharest:Pickup at our Piata Romana location. Place your order ahead for a seamless pickup experience.",
  "Delivery Methods & Fees",
  "Pickp Info",
  "",
  "Chef Marco Di Luca",
  "Executive Chef, Trattoria La Bella (New York)",
  "contact@pepper.pizza",
  "MENU",
  "123 Pizza St.Manhattan, New York, NY 10001United States",
  "delivery@pepper.pizza",
  "Monday – Friday: 9 AM – 10 PMSaturday: 10 AM – 11 PMSunday: 10 AM – 8 PM",
  "Home",
  "USEFUL",
  "SOCIAL",
  "Instagram",
  "Trip Advisor",
  "Youtube",
  "Twitter",
  "©",
  "made by",
  "UIhub.design",
  "with",
  "in",
  "Framer",
  "Made with",
  "Email",
  "Submit",
  "Thank you!",
  "Something went wrong",
  "Delicious Deals, Just for You",
  "Sign up for our newsletter and receive exclusive offers on new pizzas!",
  "Delicious Deals,Just for You",
  "Pizza Perfection, Expertly Rated",
  "Top foodies and chefs share their thoughts on why our pizzas stand out from the crowd.",
  "Name",
  "Phone",
  "Message",
  "Icons",
  "PHOSPHOR",
  "Open Link",
  "Remix Template",
  "Short Description",
  "Content",
  "Licensing",
  "Find essential licensing resources and detailsto ensure compliance and transparency.",
  "New York:",
  "113 E31st St, New York, NY 10016",
  "newyork@pepper.pizza",
  "+01 222 555 444",
  "1 Medium Firecracker Inferno",
  "1 Medium Buffalo Bliss",
  "From the classic simplicity of a traditional Margherita to the rich indulgence of gourmet truffle oil creations, we artfully blend the best of old-world charm with modern culinary innovation. Each pizza is hand-tossed with care, topped with fresh, high-quality ingredients, and baked to golden perfection.",
  "Pasta",
  "From the rustic kitchens of Italy to your table, our pasta is crafted with time-honored techniques and fresh, high-quality ingredients. Whether it’s a creamy Alfredo or a bold Arrabbiata, each dish embodies the essence of traditional Italian cuisine with a touch of contemporary flair. Every forkful is a tribute to authentic flavors, cooked to al dente perfection.",
  "Sides",
  "Our sides are the perfect blend of simple, satisfying flavors and creative culinary twists. From crispy truffle fries to golden mozzarella sticks, each bite complements your meal while standing out on its own. Made to share—or not—our sides are prepared fresh with ingredients that elevate even the smallest snack into a gourmet experience.",
  "Deserts",
  "Inspired by classic Italian sweets and modern indulgences, our desserts are the perfect finale to your dining experience. Whether it’s the velvety layers of tiramisu or the decadent richness of molten chocolate cake, each treat is carefully crafted to balance sweetness and sophistication. From first bite to last, our desserts are a sweet journey through time-honored recipes with a dash of creativity.",
  "Drinks",
  "Our drink menu offers a refreshing mix of timeless classics and bold, modern flavors. From freshly squeezed lemonades to expertly brewed iced coffee, each sip is designed to complement your meal or provide a stand-alone moment of refreshment. Whether you prefer fizzy Italian sodas or a rich cold brew, we have the perfect drink to quench your thirst and elevate your experience.",
  "All",
];

// Sonic — Product showcase / E-Commerce
const text4 = [
  "Immersive Sound, Simplified",
  "Our most recent breakthrough in audio devices blends exceptional audio performance with unparalleled toughness and elegance.",
  "Our latest innovation",
  "in portable speakers",
  "combines superior sound quality",
  "with unmatched durability",
  "Experience crystal-clear audio with deep bass and immersive sound.",
  "Our smart speaker is designed to fill your space with rich, high-fidelity sound—whether you're at home or on the go.",
  "Seamless connectivity, voice control, and a sleek, modern design make this speaker the perfect addition to any room.",
  "Designed for modern living, this speaker blends premium sound with intuitive controls.",
  "Trusted by Thousands, Engineered for Excellence",
  "Our commitment to innovation and quality has earned the trust of customers worldwide. Sleek design, our products are built to impress.",
  "Timeless Elegance",
  "Enhance your space with a perfect blend of modern design and warm ambiance. Our speaker bring style and sophistication",
  "Welcome to Beyond FAQ!",
  "Everything You Need to Know About Our Speakers",
  "Sound Insights",
  "Stay updated with the latest trends in audio technology, speaker innovations, and expert tips to enhance your listening experience.",
  "Buy now",
  "About",
  "60K",
  "Our latest innovation in portable speakers combines superior sound",
  "Features",
  "Surely there must be a better and more",
  "Our speakers deliver premium sound quality, sleek design, and long-lasting durability, ensuring an unmatched listening experience.",
  "Get yours - 30% off",
  "Title",
  "Home",
  "The Perfect Sound, Anywhere",
  "Company",
  "Legal",
  "© 2025. All rights reserved. SONIC",
  "@sonic",
  "Get your perfect speaker now!",
  "Bring every room together",
  "Experience our latest portable speaker innovation, delivering exceptional sound quality, unbeatable durability, and sleek design.",
  "Load More",
  "Tips for Speakers",
  "Public speaking is a skill that can open doors, inspire change, and leave a lasting impact.",
  "Content",
  "Back",
  "",
  "24/7 Available",
  "You can contact us via email, phone, or by filling out the form on this page. We strive to respond promptly and look forward to connecting with you soon!",
  "Write us",
  "We’d love to hear from you!",
  "First name",
  "Last name",
  "Email",
  "Location",
  "example@gmail.com",
  "Submit",
  "Thank you",
  "Something went wrong",
  "Page Not Found",
  "It looks like the page you’re looking for doesn’t exist. Maybe it was moved, deleted, or never existed in the first place.",
  "Smart. Sleek. Powerful.",
  "The Evolution of Speakers",
  "Right Speaker for You",
  "Storytelling is an ancient art that has shaped cultures, inspired movements, and connected humanity for generations",
  "Wireless Speakers",
  "Whether you are making personal, professional, or business decisions, considering key factors is essential for achieving the best outcomes. ",
  "Dolby Atmos and Beyond",
  "Gaming is another area where immersive audio is making a big impact.",
  "Eco-Friendly Audio Solutions",
  "By choosing eco-friendly speakers, you can enjoy great sound while doing your part to protect the planet.",
  "Why Size and Shape Matter",
  "Speakers are more than just boxes that emit sound.",
  "Terms of Service",
  "14 Jan 2025",
  "Privacy Policy",
  "09 Jan 2025",
];

// Serrena — Ecommerce Template
const text5 = [
  "Wear cloths that matter",
  "Best Seller",
  "Serrena Exclusive Deal",
  "Discover the epitome of style with Serrena Exclusives. Elevate your wardrobe with premium brands, where luxury meets fashion. Immerse yourself in a world of unparalleled elegance. Explore now!",
  "Featured",
  "shop",
  "You May Also Like",
  "About us",
  "Home",
  "SHOP ONLINE",
  "Explore a vast collection of premium clothing from the comfort of your home.",
  "FREE SHIPPING",
  "Enjoy the convenience of free shipping on all orders, nationwide.",
  "RETURN POLICY",
  "Your satisfaction is our priority. Return any product you are not satisfied with.",
  "PAYMENT METHODS",
  "Choose from a variety of secure payment methods to complete your transactions with ease.",
  "At the heart of Serrena lies a distinctive philosophy that transcends trends and embraces the essence of enduring style. Our collections are a harmonious blend of sophistication, versatility, and modernity, carefully curated to enhance your personal expression. We believe that fashion should empower, inspire, and reflect the unique narrative of every individual. Serrena is not just about clothing; it's about embracing a lifestyle that embraces the artistry of fashion and the poetry of self-expression.",
  "Follow @serrenA",
  "Contact us",
  "Need any help?we're here for you.",
  "Call Us",
  "+96746737637",
  "Mail",
  "hello@serrena.com",
  "Name",
  "Email",
  "Message",
  "frequently asked",
  "Shop",
  "Men",
  "Women",
  "Kids",
  "About",
  "Contact",
  "Serrena",
  "Visit Shop",
  "-NaN%",
  "Sublime Blossom",
  "$NaN",
  "Men's collection",
  "woMen's collection",
  "kids's collection",
  "Title",
  "Viscose Shirt Dress",
  "",
  "You may also like",
  "Get Upto 65% off",
  "FREE SHIPPING ON ORDERS $50+",
  "GET YOUR $20 BONUS REWARD",
  "All",
  "SeRrena",
  "Your trusted fashion companion",
  "Navigation",
  "Categories",
  "All Rights Reserved By @Cosmic Studio",
  "Sign up to our newsletter & get 20% off",
  "Question",
  "Answer",
  "BEST SELLER",
  "Urban",
  "Submit",
  "Thank you",
  "Something went wrong",
  "viscose-shirt-dress",
  "Pink Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closurePink Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure",
  "https://cosmicui.lemonsqueezy.com/checkout/buy/f5d874fb-7143-4473-b567-535ae989583c",
  "dress women shirt",
  "Straight Regular Jeans",
  "pants",
  "Cotton Twill Jacket",
  "jacket",
  "Loose Jeans",
  "Regular Fit Coated Jacket",
  "Carpenter Joggers",
  "Z.N.E. PREMIUM FULL-ZIP HOODED TRACK JACKET",
  "Oversized Crinkled Dress",
  "dress",
  "Oversized Fit Cotton T-shirt",
  "tshirt",
  "PINK TEE",
  "Black Floral Tie-Up Neck Chiffon Dress",
  "CAMO TREFOIL TEE",
  "Denim Shacket",
  "Button-detail Jacket",
  "suit",
  "Biker Jacket",
  "WOMEN SOLID SLIM FIT SINGLE BREASTED 2-PIECE FORMAL SUIT",
  "ESSENTIAL TEE",
  "Slim Fit Flared Twill Pants",
  "WOMEN BLACK SMART SLIM FIT OPAQUE COLOURBLOCKED CASUAL SHIRT",
  "shirt",
  "Cotton Jersey T-shirts",
  "Oversized Blazer",
  "Relaxed Fit Denim Jacket",
  "Gathered-sleeve Jacket",
  "Eyelet Embroidered Shirt",
  "Twill Chinos",
  "Printed Jersey Tops",
  "CITY ESCAPE PREMIUM CARGO PANTS",
  "Joggers",
  "Water-repellent Puffer Jacket",
  "RUST COLOR RUFFLE SPREAD SHIRT",
  "STRETCH WOVEN PANT",
  "Linen-blend Shirt Dress",
  "Short Sleeve Essential Embroidered Tee",
  "TERREX XPLORIC RAIN.RDY HIKING JACKET",
  "Cotton Pique Polo Shirt",
  "Linen-blend Shirt",
];

// Blocks — SaaS Website Kit
const text6 = [
  "Get started",
  "Learn more",
  "Which pricing plan is right for me?",
  "You can cancel your plan whenever you’d like. You’ll be downgraded to the free plan. You won’t be locked out of any projects that have paid plans.",
  "As a seasoned designer always on the lookout for innovative tools, Framer.com instantly grabbed my attention. This powerful web design platform is more than just a design tool - it's a complete ecosystem.",
  "Maria Cortez",
  "@mariac3203094",
  "This page is included in a free SaaS Website Kit.",
  "Pathway to productivity",
  "Celebrate the joy of accomplishment with an app designed to track your progress, motivate your efforts, and celebrate your successes.",
  "A more effective way to track progress",
  "Effortlessly turn your ideas into a fully functional, responsive, no-code SaaS website in just minutes with the set of free components for Framer.",
  "Streamlined for easy management",
  "Enjoy customizable lists, team work tools, and smart tracking all in one place. Set tasks, get reminders, and see your progress simply and quickly.",
  "Integration ecosystem",
  "Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.",
  "Goal setting and tracking",
  "Define and track your goals, breaking down objectives into achievable tasks to keep your targets in sight.",
  "Pricing",
  "Free forever. Upgrade for unlimited tasks, better security, and exclusive features.",
  "Free",
  "$0",
  "/month",
  "Pro",
  "$9",
  "Business",
  "$19",
  "What our users say",
  "Sign up for free today",
  "Celebrate the joy of accomplishment with an app designed to track your progress and motivate your efforts.",
  "Product",
  "Features",
  "Integrations",
  "Updates",
  "FAQ",
  "Company",
  "About",
  "Blog",
  "Careers",
  "Manifesto",
  "Press",
  "Contact",
  "Resources",
  "Examples",
  "Community",
  "Guides",
  "Docs",
  "Legal",
  "Privacy",
  "Terms",
  "Security",
  "Acme Corp",
  "Quantum",
  "Echo Valley",
  "PULSE",
  "APEX",
  "Celestial",
  "Welcome!",
  "Build and publish your website in minutes. Copy and paste sections and components to your project and go from concept to live site.",
  "Access all sections and elements",
  "Go to Pages on the left to view a complete collection of all the elements from the kit.",
  "Responsive design",
  "Before pasting the elements, set up breakpoints for desktop, tablet, and mobile in your Framer project. This ensures your elements look good on all devices.",
  "Go to framer.com/free-saas-kit for detailed instructions on how to use this kit and for the link to Figma project.",
  "Learn how to use the kit",
  "Tasks",
  "Organize tasks",
  "Page not found",
  "Sorry, we couldn’t find the page you’re looking for.",
  "Search",
  "Marketing",
  "Website",
  "Holiday Campaign",
  "SEO",
  "Collaborations",
  "Analytics",
  "Finances",
  "Marketing / Website",
  "Launch",
  "Design",
  "Define color scheme & typography",
  "Mar 23",
  "Done",
  "Design homepage",
  "Mar 28",
  "Design responsive layouts for mobile and tablet views",
  "Apr 12",
  "In progress",
  "Implement navigation with dropdowns",
  "Apr 18",
  "Add animations",
  "Apr 22",
  "Include CTAs",
  "Mar 29",
  "Research and integrate relevant keywords",
  "Mar 21",
  "Ensure all pages have meta titles and descriptions",
  "Set up Google Analytics",
  "Testing",
  "Conduct usability testing with a small group of users",
  "Apr 28",
  "Test on different devices and browses for compatibility",
  "Apr 20",
  "SaaS Website Kit",
  "One Task",
  "at a Time",
  "Celebrate the joy of accomplishment with an app designed to track your progress, motivate your efforts, and celebrate your successes, one task at a time.",
  "Trusted by the world’s most innovative teams",
  "Everything you need",
  "Intuitive interface",
  "Frequently asked questions",
  "Get instant access",
  "© 2024 Your Company, Inc. All rights reserved.",
  "Official Framer Resource",
  "Track your progress and motivate your efforts everyday.",
  "Up to 5 project members",
  "Slack channel and dedicated account manager",
  "SaaS Conf 2024",
  "・",
  "Dive into the Future of SaaS",
  "50% off all plans",
  "Limited time only",
  "Heading 1",
  "Heading 2",
  "Heading 3",
  "Heading 4",
  "Heading 5",
  "Version 2.0 is here!",
  "Link",
  "Customers",
  "Help",
  "Dedicated support",
  "We have worked with hundreds of amazing people",
  "“This app has completely transformed how I manage my projects and deadlines.”",
  "Jamie Teller",
  "CEO & Founder",
  "“Our team’s productivity has skyrocketed since we started using this tool. ”",
  "Jordan Patels",
  "Marketing Designer",
  "“The customizability and integration capabilities of this app are top-notch.”",
  "Taylor Kim",
  "Celebrate the joy of accomplishment with an app designed to track your progress.",
  "Your pathway to better productivity",
];

// Flair-SaaS-AI-Web3-Template
const text7 = [
  "Header",
  "Trusted by the best companies in the world.",
  "Graphite helps you to scaleyour business to the next level",
  "Graphite is packed with features that allow you to focus on the essentials.",
  "What Our Clients Are Saying",
  "Discover how Graphite has transformed businesses with its seamless integration, intuitive design, and powerful features.",
  "Boost your productivity",
  "Graphite improves your processes and transforms your business for you.",
  "Superior Performance",
  "Our platform consistently outperforms competitors in speed and efficiency, thanks to cutting-edge technology and optimized infrastructure.",
  "Graphite",
  "Performance score: 400",
  "Competitor 1",
  "Performance score: 220",
  "Competitor 2",
  "Performance score: 140",
  "Lightning Fast",
  "Loading times optimized for seamless experience for your users.",
  "Seamless Integration",
  "Integrate Flair with all your favorite apps in just a few clicks.",
  "AI Updates",
  "Our data centers are powered by green energy, reducing our carbon footprint and supporting a cleaner planet.",
  "Smart Folders",
  "Real-time, data-driven insights that help you make smarter decisions and uncover hidden opportunities.",
  "Simple, Transparent Pricing",
  "Frequently Asked Questions",
  "Here is our most frequently asked questions. If you can't find what you are looking for don't hesitate to contact us.",
  "The latest updates from Flair",
  "Get this template for FREE",
  "All the features to scale your business to the next level",
  "Our platform consistently outperforms competitors in speed and efficiency.",
  "Creator",
  "Hi! I'm Toni, the creator of this template.Feel free to reach out to me via my e-mail tonjrv@gmail.com. Or if you prefer, send me a message in X (Twitter): @tonjrvAlso, I'd love to see the end results with the template so feel free to share and ping me in Twitter: @tonjrv",
  "Text",
  "Date",
  "Title",
  "Content",
  "Copy",
  "Facebook",
  "Instagram",
  "X/Twitter",
  "TikTok",
  "Title1",
  "Title2",
  "Join the future",
  "Trusted by 10 000+ companies all over the world.",
  "FAQ",
  "Contact",
  "Home",
  "How it works",
  "Testimonials",
  "Features",
  "Pricing",
  "News",
  "Copyright @2024",
  "Footer link",
  "Introducing our product",
  "Load More",
  '"Graphite has transformed the way we manage our projects. The intuitive interface and seamless integration made the setup a breeze, and the real-time analytics have been a game-changer for our decision-making process. Highly recommend!"',
  "Name",
  "Company",
  "Which pricing plan is right for me?",
  "You can cancel your plan whenever you’d like. You’ll be downgraded to the free plan. You won’t be locked out of any projects that have paid plans.",
  "Email",
  "Message",
  "Place logos inside the logo layer, and resize them to fit the circle.Connect the logos to Tickers on Variant 1.You can find logos from this site: https://simpleicons.org/",
  "Feature",
  "Next",
  "API Integration",
  "Easy connectivity with the API integration.",
  "Your sales have been decreasing lately, potentially because of this and that.",
  "Submit",
  "We got your message!",
  "Something went wrong",
  "Starter plan",
  "$29/month",
  "5 users",
  "Basic AI analytics",
  "10 GB of storage",
  "Access to all core features",
  "5 Ways to Maximize Efficiency with Flair",
  "Why Sustainable Technology is the New Standard",
  "How to Seamlessly Integrate Flair into Your Existing Tech Stack",
  "The Importance of AI-Driven Decision-Making",
  "Why Your Business Should Switch to Graphite",
  "How AI is Transforming Customer Support",
];

// Groomify — Pet Grooming Template - error
// const text8 =

// Billie — Immersive Premium Portfolio
const text9 = [
  "Selected work",
  "Hello thereI’m Billie Duvalle",
  "Specializing in branding and design, I try to bring a distinctive, expressive flair to my work, blending my multicultural background with a keen eye for bold, innovative visual storytelling. My creative vision spans various mediums, crafting compelling brand identities that resonate with diverse audiences and leave a lasting impression.",
  "Services",
  "Graphic DesignPackagingArt DirectionBrand StrategyCopywritingNamingCommunicationDigital DesignUX/UI Design",
  "Clients",
  "NikeAdidasFordBurger KingHeinekenGoogleInstagram",
  "Let’s talk",
  "What's this component?A workaround to have consistent and decent padding in page and easy to change everywhere",
  "Title",
  "INSTAGRAM",
  "LINKEDIN",
  "TWITTER",
  "250 Park AveNUE STREETNew York, NY 10003United States",
  "Do you likeWhat you see?",
  "2024 ® BILLIE DUVALLE",
  "Connect",
  "Hero Title",
  "Nothing to see here, 404",
  "Dutch born, Japanese raised art director based in Cape Town focusing on branding & design in expressive forms.",
  "Pad/gap 48px deskPad/gap 20px mobContainer Max width 1800Gridgap: 48px desk / 20px mobEnter on scroll: opacity 0, scale 1, y 30, spring 180-40-1-0",
  "Heading 1",
  "Heading 2",
  "Heading 3",
  "Heading 4",
  "Heading 5",
  "Heading 6",
  "Body",
  "Body small",
  "Body micro",
  "Colors",
  "White, #FFFFFF",
  "Black, #0F0E0E",
  "BILLY DUVALLE",
  "WORK",
  "ABOUT",
  "CONTACT",
  "®2024",
  "Get the template",
  "Philly’s: Boston ice cream history",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec porttitor risus, non luctus augue. Nulla et accumsan lacus, et finibus lectus. Praesent et elit est. Nam eget semper augue.",
  "Client",
  "A",
  "DELIVERABLES",
  "Year",
  "Role",
  "Next Project",
  "Work we’re proud of",
  "over the years I completed hundreds of projects with several clients. Here is a selection of the best ones.",
  "Philly’s Ice Cream",
  "REBRANDING",
  "We started from one strong belief: that in today's world, new and memorable experiences constitute our true personal luxury. We are convinced that these unique moments are what enrich our lives and leave a lasting impact. So here's to the memories in the making, to those extraordinary experiences that become the stories we cherish and share. ",
  "2021",
  "Creative Direction",
  "Photography\nBranding",
  "Gaston: Lighting under a new light",
  "Gaston",
  "Sensaya: Beauty for everyone",
  "Senseya",
  "LeBlink: Skincare for the modern age",
  "Le Blink",
  "Schlong: The subtle art of fine living",
  "Schlong",
  "Vintage Everything: Fashion Hunters",
  "Vintage Everything",
];

// Athos 2.0 — Framer Portfolio Template
const text10 = [
  "Text",
  "Almost before we kne",
  "Your Strategic Partner for Digital Solutions",
  "Supporting text",
  "Tools which I use on a daily basis.",
  "Explore My Projects",
  "Our works are a blend of innovative thinking and practical solutions, ensuring they are both unique and effective.",
  "Trusted by Professionals",
  "While most of my client reviews are NDA-protected (because, you know, top-secret agency white label stuff), I managed to sneak in a few favorites from my previous partners.",
  "Quote",
  "Process",
  "Your compass to innovation and design excellence. From exploration to execution, this dynamic framework fuels creativity and precision, ensuring your product journey aligns seamlessly with user desires.",
  "Trusted by a New Generation of Companies",
  "87 %",
  "reduction in hiring costs",
  "20 Jan 2024",
  "Finding, hiring and managing remote tech talent with Athos has never been faster, easier or more flexible.",
  "Athos has allowed us to deliver on relevant projects on time and strengthened our team.",
  "7x",
  "Faster than traditional hiring",
  "Frequently Asked Questions",
  "Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.",
  "We Create only Awesome Branding",
  "Budget Planner Finance App",
  "Industry",
  "Fintech",
  "Headquarters",
  "London",
  "Founded",
  "2018",
  "Company size",
  "1 - 20",
  "Content",
  "12",
  "years experience",
  "01 Research & Analysis",
  "02 Information Architecture",
  "03",
  "Wireframing & Prototyping",
  "04 Usability Testing",
  "05 Visual Design & Style Guide",
  "Footer text",
  "Figma",
  "Design Tool",
  "Framer",
  "Website Builder",
  "Relume",
  "The fastest way to design and build a website",
  "Webflow",
  "Hotjar",
  "Behaviour Tool",
  "Heading",
  "Spline",
  "Place to design and collaborate in 3D",
  "Design tool for creating and collaborating",
  "Framer is where teams design and publish stunning sites.",
  "Access the world’s largest library of Figma",
  "Take control of HTML, CSS, and JavaScript in a visual canvas.",
  "Behaviour analytical tool to track users",
  "Notion",
  "Wiki, docs and projects management system",
  "Button Text Large",
  "Get 60% Off on Athos 2.0 Pro! Join the Pre-Launch Waitlist Now",
  "Fireflies AI",
  "AI Notetaker for Meetings",
  "Goran Babarogic - Framer Expert",
  "Goran Babarogic",
  "Oopsie",
  "The page you are looking for doesn't exist or has been moved.",
  "Edit in Framer",
  "Remix Project",
  "With user-centered approach, the goals was to create an intuitive interface for effortless financial management while incorporating gamification.",
  "Awesome visual identities & logo(s)",
  "Berlin",
  "2010",
  "50-101",
  "Improved Onboarding Process",
  "35%",
  "Increase in User Retention",
  "25%",
  "Increase in Time Spent on Website",
  "84%",
  "Bitbo - Bitcoin Stats & Data",
  "Digital Product Design Solution",
  "Design for Internet Sharing App",
];

// Arik — Modern Portfolio Template
const text11 = [
  "Web Designer & Developer",
  "Premium Web Design, Development, and SEO services to help your business stand out.",
  "01",
  "Web design",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "02",
  "Development",
  "Content & Seo",
  "Selected Work",
  "THe PRocess",
  "Your Website in 5 steps",
  "Premium web design, webflow, and SEO services to help your business stand out.",
  "Do we Match?",
  "Discovery Call",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et malesuada fames ac turpis egestas integer eget aliquet. Ac auctor augue mauris augue neque gravida in fermentum.",
  "Lorem ipusm dolor",
  "Ac auctor augue mauris augue",
  "Et malesuada fames ac turpis",
  "What my clients say",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
  "Amazing Results with Aiko's Premium Web Design Services.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et malesuada fames ac turpis egestas integer eget aliquet. Ac auctor augue mauris augue neque.",
  "John Smith",
  "ABC Company",
  "Professional, Collaborative Web Design Experience with Aiko.",
  "Karen Lee",
  "Redwood Technologies",
  "Web Design and Content Solutions: Stand Out from the Crowd.",
  "Emily Davis",
  "Greenway Industries",
  "Expert Webflow and SEO Services: Excellent Work, Great Results.",
  "David Kim",
  "Design Inc.",
  "Expertise in Web Design: Second to None with Aiko.",
  "Andrew Thompson",
  "Silverstone Corporation",
  "High-Quality Web Design: Exceptional Attention to Detail with Aiko.",
  "Ryan Chen",
  "Golden Gate Solutions",
  "Arik Andersson",
  "A website that leaves a lasting impression!",
  "Web Design & Framer",
  "Premium web design, development, and SEO services to help your business stand out.",
  "Clients",
  "150+",
  "Projects",
  "300+",
  "Happy Clients",
  "100%",
  "Followers",
  "100k",
  "Webdesign",
  "Create a brand experience that engages and inspires.",
  "Wireframes",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut diam quam nulla porttitor.",
  "Figma Prototype",
  "Brand messaging",
  "Delivering Premium Web Design and Development Services to Boost Your Online Presence.",
  "Your Partner in Bringing Your Web Design Vision to Life",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat nam at lectus urna duis convallis. Sem fringilla ut morbi tincidunt. Velit egestas dui id ornare arcu odio ut sem. Neque sodales ut etiam sit amet nisl purus. Egestas erat imperdiet sed euismod nisi porta lorem. A diam maecenas sed enim ut sem viverra.",
  "Awards",
  "Awwwards SOTD",
  "2023",
  "CSSDA SOTD",
  "Awwwards Website of the Month",
  "2022",
  "2021",
  "Pricing",
  "Experience the Power ofPremium Web Design",
  "Choose a package that suits your needs and budget. Transparent pricing with no hidden fees.",
  "Lite",
  "$3900.00 USD",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.",
  "Concept",
  "Strategy",
  "Prototype",
  "Premium",
  "$6900.00 USD",
  "Webflow Development",
  "Gold",
  "$9900.00 USD",
  "Content",
  "SEO",
  "FAQ",
  "Common Questions",
  "Contact",
  "Let's get in touch",
  "Work",
  "My latest web design projects and see how we can help bring your ideas to life.",
  "Services",
  "About",
  "Blog",
  "Styleguide",
  "Project in mind?",
  "Let’s make your Website shine",
  "Lorem ipsum Dolor",
  "+++",
  "Instagram",
  "Twitter",
  "Dribbble",
  "Behance",
  "Pages",
  "Home",
  "CMS",
  "Work Single",
  "Blog Post",
  "Utility Pages",
  "404 Error Page",
  "Licensing",
  "© Made by Gola Templates. Powered by Framer.",
  "Space",
  "Client",
  "Pawel Gola",
  "Timeline",
  "3 Weeks",
  "Template",
  "Website",
  "gola.io",
  "Brand Services",
  "01 · Branding",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Massa tempor nec feugiat nisl.",
  "Get the latest insights and tips on web design, development, and SEO in our blog.",
  "All graphical assets in this template are licensed for personal and commercial use. If you'd like to use a specific asset, please check the license.",
  "Images",
  "Unsplash",
  "Image Collection",
  "License",
  "Ls.graphics",
  "Iphone Mockups",
  "Macbook Mockups",
  "Fonts",
  "Satoshi",
  "Source",
  "Gambetta",
  "Headings",
  "Heading XLarge",
  "Heading Large",
  "Heading Medium",
  "Heading Small",
  "Heading H1",
  "Heading H2",
  "Heading H3",
  "Heading H4",
  "Heading H5",
  "Heading H6",
  "Button",
  "Default",
  "Primary",
  "Secondary",
  "Button Text",
  "Button Scroll",
  "Label",
  "Default Link",
  "Primary Link",
  "Secondary Link",
  "Badge",
  "Default Icon",
  "Nav",
  "To Top Scroll",
  "Alvy",
  "My Services",
  "Integer vitae justo eget magna?",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Tincidunt vitae semper.",
  "16th June 2022",
  "How to Build a Stunning Website with Framer",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.",
  "Available for work",
  "March",
  "Not Available",
  "April",
  "1 Spot",
  "May",
  "2 Spots",
  "Nav Item",
  "Elit ullamcorper dignissim",
  "Conclusion",
  "Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Massa vitae tortor condimentum lacinia quis vel. Hendrerit dolor magna eget est lorem ipsum dolor. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id.",
  "Framer Expert",
  "Use for FREE",
  "More Templates",
  "Modern and visually appealing website that reflected the client's brand.",
  "2 Weeks",
  "Web Design",
  "Concept, Design, and Development. All-in-one.",
  "Our client was struggling to attract and retain customers due to an outdated and non-responsive website that didn't align with their brand identity.",
  "Our goal was to create a modern and visually appealing website that reflected the client's brand and delivered a seamless user experience. The website needed to be responsive, easy to navigate, and optimized for search engines to improve their online visibility.",
  "Our team developed a custom website design that was not only visually stunning but also user-friendly and optimized for search engines. The client's website now showcases their products and services in a professional and engaging manner, and has seen a significant increase in organic traffic and customer engagement. The client is thrilled with the final result and has received positive feedback from their customers.",
  "Nova",
  "Gola.io",
  "Sonic",
  "Solar",
  "2 Min",
  "Learn how to create an impressive website using Framer with our step-by-step guide.",
  "10 website elements for maximum user engagement",
  "10 website elements to engage users, from intuitive navigation to compelling visuals.",
  "The importance of content in driving website traffic",
  "Quality content is king. Learn how to create valuable, SEO-optimized content.",
  "10 common web development mistakes to avoid",
  "10 common web development mistakes and improve your site's functionality and user experience.",
  "Why responsive web design is critical for your business",
  "Responsive web design ensures your site looks great and performs well on all devices.",
  "How to write content that ranks on Google",
  "Optimize your website with expert tips on writing content that ranks high on Google.",
];

// NajmAI
const text12 = [
  "Your AI-Powered Design Assistant",
  "Unlock your creative potential. Seamlessly generate, customize, and perfect your designs with cutting-edge AI technology.",
  "More Templates",
  "Unleash Your Creativity",
  "Discover how our AI-Powered Design Assistant transforms your ideas into stunning designs effortlessly. Follow these simple steps to turn your vision into reality.",
  "High-Resolution Outputs",
  "Download your final designs in high-resolution formats suitable for print and digital use. Ensure your work looks professional and polished in any medium.",
  "Real-Time Collaboration",
  "Seamlessly collaborate with your team in real-time. Share ideas, give feedback, and make edits together, no matter where you are.",
  "Advanced Scheduling Tools",
  "Plan and schedule your design projects with ease. Use our scheduling tools to set deadlines, track milestones, and ensure timely delivery of your design work.",
  "Transforming Imagination into Reality",
  "Unlock the full potential of your creativity with our AI-powered design assistant. Explore new dimensions of design, from futuristic visuals to timeless craftsmanship, and witness how AI can turn your wildest ideas into stunning realities.",
  "Affordable Plans for Every Need",
  "Choose the perfect plan for your design projects, from startups to enterprises. Our pricing tiers are designed to offer flexibility and value, ensuring you get the most out of our AI-powered design assistant.",
  "Seamless Tool Integration",
  "NajmAI offers seamless integration with a variety of popular design and project management tools, ensuring a smooth and efficient workflow.",
  "Customer Success Stories",
  "Discover how our platform has helped businesses create outstanding content effortlessly. Hear directly from our users about their success and satisfaction.",
  "Stay Inspired with Our Latest Insights",
  "Dive into our blog for the latest trends, tips, and insights in the world of design and AI technology. Whether you’re looking for inspiration, tutorials, or industry news, our articles are crafted to keep you informed and inspired.",
  "30% off a Framer pro plan",
  'Use code "partner25proyearly" at checkout to claim.',
  "Available only for Yearly Subscription",
  "Built something with this template? Share it with us and get featured on our 'Built with Templyo' page—plus a backlink to boost your SEO!More Details: https://templyo.io/built-with-templyo",
  "Get Started",
  "NajmAI",
  "How it Works",
  "Features",
  "Pricing",
  "Blog",
  "Faqs",
  "Contact",
  "Made by Templyo | Powered by Framer",
  "Privacy Policy",
  "Terms & Conditions",
  "Powered by Framer",
  "Home",
  "Upload Brief",
  "Share your project details and let our AI grasp your vision.",
  "Dive into the world of AI where design possibilities are limitless. Let the cutting-edge technology transform your concepts into breathtaking visuals.",
  "Witness the Future",
  "Monthly",
  "Yearly",
  "FREE",
  "$0/m",
  "Free forever",
  "Basic AI-generated designs",
  "Access to customization tools",
  "Standard templates library",
  "5 projects per month",
  "BASIC",
  "$14.99/m",
  "Billed Monthly",
  "Advanced AI-generated designs",
  "Full access to customization tools",
  "Premium templates library",
  "Unlimited projects",
  "Real-time collaboration",
  "Priority email support",
  "PRO",
  "$29.99/m",
  "All features included in Pro Plan",
  "Dedicated account manager",
  "Custom AI solutions and designs",
  "Onboarding and training sessions",
  "24/7 priority support",
  "Advanced analytics and reporting",
  "Secure cloud storage",
  "$11.93/m",
  "Billed Yearly",
  "$24.93/m",
  "Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.",
  "404",
  "John Doe",
  "Using this platform has transformed our content creation. The AI-generated copy is high-quality and saves us a lot of time. It's like having a professional copywriter on our team 24/7.",
  "Content",
  "Jan 1, 1970",
  "Title",
  "Use for FREE",
  "Start Your Design Journey Today",
  "Sign up now and experience the power of AI-driven design without any commitment.",
  "Date",
  "Read Time",
  "Read More",
  "Contact Us",
  "Have questions or need help? Fill out the form below, and we'll get back to you promptly. We're here to assist you!",
  "Name",
  "Email",
  "Message",
  "Frequently Asked Questions",
  "Have questions about our AI-Powered Design Assistant? Find answers to the most common questions and learn how our platform can enhance your creative process.",
  "Submit",
  "Thank you",
  "Something went wrong",
  "Get 3 FREE Months on Framer Pro Plan",
  'Use code "partner25proyearly" at checkout',
  "Starting and Growing a Career in Web Design",
  "6 min read",
  "Create a Landing Page That Performs Great",
  "5 min read",
  "How Can Designers Prepare for the Future?",
  "7 min read",
  "Building a Navigation Component with Variables",
  "How to Create an Effective Design Portfolio",
  "How does the AI generate designs?",
  "Our AI analyzes your design brief and uses advanced algorithms to generate multiple design concepts tailored to your specifications. It takes into account your preferences, style, and project requirements to deliver unique and high-quality designs.",
  "Can I customize the AI-generated designs?",
  "Yes, our platform includes powerful customization tools that allow you to refine and perfect your chosen designs. You can make adjustments, add elements, and tweak details to ensure the final design matches your vision.",
  "What support options are available?",
  "We offer comprehensive support for all our plans. Starter users have access to email support, Pro users benefit from priority email support, and Enterprise users receive 24/7 priority support along with a dedicated account manager.",
  "Is there a free trial available?",
  "Yes, we offer a 14-day free trial for all new users. You can explore all the features of our AI-powered design assistant and see how it can enhance your creative process before committing to a subscription.",
  "How secure is my data?",
  "We prioritize the security of your data. All your designs and project details are stored in secure cloud storage with advanced encryption. Enterprise users have access to enhanced security options for added peace of mind.",
  "What integrations are available?",
  "Our platform seamlessly integrates with popular design and project management tools such as Adobe Creative Suite, Figma, and Trello. This allows you to streamline your workflow and easily incorporate our AI-powered design assistant into your existing processes.",
];

// Qitchen — Restaurant Template
const text13 = [
  "SushiSensation",
  "Button",
  "Web Design",
  "Menu",
  "Maki",
  "UraMaki",
  "Special Rolls",
  "Booka table",
  "Reservation",
  "Secure your spot at Qitchen, where exceptional sushi and a remarkable dining experience await.",
  "About",
  "Sushi Artistry Redefined",
  "Where culinary craftsmanship meets modern elegance. Indulge in the finest sushi, expertly curated to elevate your dining experience.",
  "Trip Advisor",
  "Best Sushi",
  "Michelin Guide",
  "Quality Food",
  "Start Dining",
  "Cool vibe",
  "Our Story",
  "Founded with a passion for culinary excellence, Qitchen's journey began in the heart of Prague. Over years, it evolved into a haven for sushi enthusiasts, celebrated for its artful mastery and devotion to redefining gastronomy.",
  "Contact",
  "OpeningHours",
  "Mon",
  "16:00 - 22:30",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat & Sun",
  "Get in touch",
  "Address",
  "23 Greenfield Avenue,Prague 120 00",
  "Phone",
  "+42 1234 567890",
  "Email",
  "info@qitchen.com",
  "Follow",
  "Opening Hours",
  "Blog",
  "Latest News",
  "Licensing",
  "All graphical assets in this template are licensed for personal and commercial use. If you'd like to use a specific asset, please check the license.",
  "Images",
  "Pexels",
  "Image Collection",
  "License",
  "Other",
  "Map",
  "Source",
  "Styleguide",
  "Headings",
  "XLarge",
  "Heading Large",
  "Heading Medium",
  "Heading Small",
  "Heading H1",
  "Heading H2",
  "Heading H3",
  "Heading H4",
  "Heading H5",
  "Heading H6",
  "Default",
  "Muted",
  "Primary",
  "Button Text",
  "Button Icon",
  "Label",
  "Label Link",
  "Badge",
  "Badge Link",
  "Nav",
  "Accordion",
  "Integer vitae justo eget magna?",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Tincidunt vitae semper.",
  "24th Aug 2023",
  "Join us for an Evening Soiree at La Paloma!",
  "",
  "404",
  "Unfortunately the page you are looking for could not be found.",
  "Button Icon Text",
  "© Gola Templates",
  "Title",
  "$29",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
  "Content",
  "Excerpt",
  "Submit",
  "Thank You",
  "Something Went Wrong",
  "Use for FREE",
  "More Templates",
  "How Qitchen Redefines Flavor Harmony in Every Bite",
  "Experience an orchestra of tastes as Qitchen's sushi unveils a symphony of perfectly balanced flavors.",
  "Unveiling the Mastery Behind Our Culinary Craftsmanship",
  "Explore the meticulous artistry and dedication that create Qitchen's renowned sushi perfection.",
  "Journey through Freshness Exquisite Sushi Selection",
  "Embark on a seafood adventure, guided by Qitchen's fresh and exquisite sushi creations from the sea.",
  "Palate with Qitchen's Unsurpassed Sushi Delicacies",
  "Discover the heights of gastronomic delight as Qitchen's sushi transports you to a new culinary realm.",
  "The Qitchen Experience Beyond Sushi",
  "Immerse in Qitchen's passion for culinary excellence, where sushi is more than a dish—it's an experience.",
];

// Dentify — Free Dental Template
const text14 = [
  "Bringing brighter smiles to your family",
  "Experience personalized dental care designed to meet your unique needs. From preventive checkups to advanced oral health and confidence are always at their best.",
  "Contact us",
  "(123) 456 789",
  "A commitment to healthier, brighter smiles",
  "Personalized solutions for better oral health",
  "Why choose us:",
  "We are dedicated to providing exceptional dental care that prioritizes your comfort, convenience, and lasting results. Here’s what makes us stand out:",
  "Delivering more than just dental care & ideas",
  "The process of achieving dental excellence",
  "01",
  "Schedule your visit",
  "Book an appointment at your convenience through our easy scheduling system, and we’ll ensure a hassle-free experience from the start.",
  "02",
  "Personalized consultation",
  "Meet with our expert dental team to discuss your needs, goals, and tailored treatment options designed just for you.",
  "03",
  "Begin your journey",
  "Medical knowledge and practices continually evolve perfectly match your goals of treatment complications with early intervention.",
  "What our patients say about us & service!!",
  "Stay updated with dental wellness tips",
  "Answers to your most common concerns",
  "Get 3 Months Free 🤩",
  "Get 3 months free when you upgrade to the Pro Plan. After upgrading, enjoy an additional 3-month free plan with the code partner25proyearly",
  "Template Info",
  "Dentify is a sleek and clean Framer template built for dental clinics and hospitals, perfect for booking appointments and showcasing services.If you’d like to edit this template, email me at: muzamalhussainghoto@gmail.comNeed help? Feel free to reach out via email as well.",
  "Which plan do I need to buy?",
  "Basic plans are ideal if you want to upgrade your site. This template supports 3 CMS collections, but for 3 collections, you'll need to upgrade to a higher Pro plan.",
  "Get matched",
  "Therapy plans",
  "Every session is customized to meet your unique needs, ensuring a focused and effective healing experience.",
  "95%",
  "Client Retention",
  "Excellent support, fast and very didactic answers. The design meets the expecta, the data import develops",
  "Daniel Smith",
  "BEFORE",
  "AFTER",
  "(253) 456 - 1189",
  "Submit",
  "Thank you",
  "Something went wrong",
  "Subscribe for exclusive content & news",
  "Enter your company email…",
  "Dentify",
  "Innovative solutions, proven success & growth",
  "Footer link",
  "Main Pages",
  "Follow us",
  "Home",
  "A modern dental care home for families",
  "Dedicated to providing exceptional dental care that combines advanced techniques",
  "Caring for your family’s oral health needs",
  "We are committed to delivering exceptional dental care with precision and compassion. Our goal is to ensure your oral health while creating beautiful, confident smiles.",
  "Watch video",
  "A trusted partner for all your dental needs",
  "Our Mission:",
  "Provide exceptional dental care that promotes lifelong oral health, enhances confidence, and prioritizes patient comfort through personalized and treatments.",
  "Expertise, precision, and care for every patient",
  "Patient-centered care",
  "Focused on your comfort and satisfaction at every visit.",
  "Cutting-edge technology",
  "Delivering precise, efficient treatments using advanced tools.",
  "Professionals committed to exceptional care",
  "Expertise in preventive and restorative care",
  "Reach out for assistance and expert care",
  "Name",
  "Email Address",
  "Phone Number",
  "Message",
  "Address",
  "8502 Preston Rd. Inglewood, Maine 98380",
  "Looking to Therapist!!!",
  "A Brighter Smile",
  "Professional teeth hinting an regulars cleanings can significantly enhance the brightness of your smile. This simple powerful improvement!",
  "4.9",
  "Preventive dentistry",
  "Regular check-ups, cleanings, and oral hygiene education to keep your teeth.",
  "Using modern technology to dental disease.",
  "Here's how to decorate your new home from scratch",
  "20th August 1947",
  "3 min read",
  "What is Framer",
  "Framer is No code website Building tool",
  "Amstedem, Netherland",
  "Grand Conference Hall 881 7th Ave New York, NY",
  "Twitter",
  "Muzamal Hussain",
  "Designation",
  "1561-447-8444",
  "Pediatric Dentistry",
  "Gentle and specialized dental care for growing smiles with all.",
  "About Service",
  "",
  "Sophia Hayes",
  "Cosmetic Dentist",
  "Contact Info",
  "Introduction:",
  "Dr. Sophia Hayes is a skilled cosmetic dentist with a passion for creating beautiful, natural-looking smiles. With a keen eye for aesthetics and over 8 years of experience, she combines artistry with advanced techniques to transform smiles and boost confidence. Patients value her dedication to detail and her ability to craft personalized solutions.",
  "Experience:",
  "Availability",
  "NaN min read",
  "Content",
  "How to prevent cavities with simple daily habits",
  "404",
  "Oops! The page you're looking for doesn’t exist, let’s get you back on track!",
  "Talk to us about your dental concerns",
  "Phone number",
  "Email address",
  "Select date*",
  "Friendly dental exams tailored for children",
  "Fluoride treatments to strengthen developing teeth",
  "Sealants for added cavity protection",
  "Gentle care for teething and early decay issues",
  "Guidance on lifelong oral hygiene habits",
  "Emergency Care",
  "Quick and reliable dental care for unexpected emergencies.",
  "Rapid treatment for toothaches and infections",
  "Expert care for chipped or broken teeth",
  "Immediate solutions for knocked-out teeth",
  "Trauma management for injuries to teeth and gums",
  "Same-day appointments for urgent cases",
  "Orthodontic Solutions",
  "Achieve a straighter, healthier smile with modern orthodontic treatments.",
  "Traditional braces for comprehensive alignment",
  "Clear aligners for discreet and flexible treatment",
  "Bite correction to improve jaw alignment",
  "Solutions for all ages, including children and adults",
  "Custom treatment plans tailored to individual needs",
  "Cosmetic Enhancements",
  "Enhance your smile’s appearance with personalized cosmetic dental treatments.",
  "Professional teeth whitening for radiant results",
  "Custom veneers for a flawless finish",
  "Tooth-colored bonding for minor corrections",
  "Clear aligners for discreet straightening",
  "Personalized treatment plans for your ideal smile",
  "Restorative Dentistry",
  "Restore the function and beauty of your smile with advanced dental treatments.",
  "Protective crowns for damaged teeth",
  "Durable fillings that match your natural teeth",
  "Custom bridges and implants for missing teeth",
  "Root canal therapy to save infected teeth",
  "Comprehensive solutions for long-lasting results",
  "Preventive Care",
  "Protect your oral health with routine checkups and preventive treatments carefully.",
  "Regular dental exams for early detection",
  "Thorough cleaning for plaque and tartar removal",
  "Fluoride treatments for cavity prevention",
  "Sealants to protect vulnerable teeth",
  "Education on personalized oral care",
  "Tue-Fri, 10:00 AM - 4:00 PM",
  "sophia.hayes@example.com",
  "(654) 987-3210",
  "Staten Island, NY",
  "Noah Bennett",
  "Endodontist",
  "Mon, Wed, and Fri, 10:00 AM - 5:00 PM",
  "noah.bennett@example.com",
  "(789) 123-4560",
  "Bronx, NY",
  "Dr. Noah Bennett is an experienced endodontist who specializes in saving teeth through root canal treatments and other advanced procedures. With a calm demeanor and a focus on patient comfort, Dr. Bennett has built a reputation for delivering precise and pain-free care.",
  "Liam Brooks",
  "Periodontist",
  "Wed-Sat, 9:00 AM - 2:00 PM",
  "liam.brooks@example.com",
  "(321) 654-9870",
  "Queens, NY",
  "Dr. Liam Brooks is a specialist in gum health and dental implants, with a focus on preventing and treating periodontal diseases. With a career spanning over a decade, Dr. Brooks combines technical expertise with a compassionate approach, ensuring patients achieve optimal oral health and confidence.",
  "Michael Reed",
  "Orthodontist",
  "Mon-Fri, 11:00 AM - 6:00 PM",
  "michael.reed@example.com",
  "(456) 789-1230",
  "Manhattan, NY",
  "Dr. Michael Reed is a seasoned orthodontist with a passion for helping patients achieve perfectly aligned smiles. With over 12 years of experience, he specializes in braces, clear aligners, and jaw alignment treatments. Dr. Reed’s meticulous approach ensures patients receive customized care tailored to their unique dental needs.",
  "Ethan Wells",
  "Pediatric Dentist",
  "Tue-Sat, 10:00 AM - 4:00 PM",
  "ethan.wells@example.com",
  "(987) 654-3210",
  "Brooklyn, NY",
  "Dr. Ethan Wells specializes in pediatric dentistry, focusing on providing a fun and welcoming experience for children. With over a decade of experience, he ensures that young patients feel at ease while receiving the best possible care. Dr. Wells is dedicated to creating healthy dental habits that last a lifetime.",
  "Amelia Carter",
  "Chief Dental Surgeon",
  "Mon-Fri, 9:00 AM - 5:00 PM",
  "amelia.carter@example.com",
  "(123) 456-7890",
  "New York, NY",
  "Dr. Amelia Carter is a highly skilled and compassionate dental surgeon with over 15 years of experience in advanced dentistry. She specializes in restorative and cosmetic dental procedures, helping patients achieve functional and aesthetic smiles. Known for her gentle approach and attention to detail, Dr. Carter is dedicated to making every patient feel comfortable and confident during their dental journey.",
  "Top reasons to replace missing teeth promptly",
  "The connection between gum health and overall wellness",
  "Why early orthodontic care is essential for children",
  "How professional teeth cleanings protect your oral health",
  "The importance of preventive dental care for long-term health",
];

//  Latte — Restaurant & Cafe Menu Template
const text15 = [
  "Header",
  "Copy",
  "Name",
  "Get this template for FREE",
  "Creator",
  "Hi! I'm Toni, the creator of this template.Feel free to reach out to me via my e-mail tonjrv@gmail.com. Or if you prefer, send me a message in X (Twitter): @tonjrvAlso, I'd love to see the end results with the template so feel free to share and ping me in Twitter: @tonjrv",
  "Text",
  "Video instructions",
  "You can also find the video instructions from the following link:https://youtu.be/Q2J-n2AIh50",
  "Google Maps",
  "5.0",
  "Latte Haven123 Latte LaneLatte City, FC 12345",
  "Food/drink name",
  "Description",
  "Date",
  "Title",
  "Content",
  "Brewed to perfection",
  "Opening hours:Mon - Thu: 11:00 AM - 9:00 PMFri - Sat: 11:00 AM - 10:00 PMSun: 12:00 PM - 8:00 PM",
  "Phone:(555) 987-6543",
  "Location:Burger Haven123 Burger LaneFood City, FC 12345",
  "Copyright @2024",
  "Footer link",
  "Title1",
  "Title2",
  "Latte",
  "Location:Latte Haven123 Latte LaneFood City, FC 12345",
  "The Art of the Perfect Latte",
  "Exploring the World of Coffee Origins",
  "5 Ways to Elevate Your Coffee Experience at Home",
  "Eco-Friendly Practices at Latte Haven",
  "Seasonal Specials at Latte Haven: Summer Edition",
];

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_KEY,
});

async function name() {
  try {
    // const model = "nateraw/nous-hermes-2-solar-10.7b:1e918ab6ffd5872c21fba21a511f344fd12ac0edff6302c9cd260395c7707ff4";

    // 2
    const model = "meta/meta-llama-3-8b-instruct";
    // input: {
    //   top_p: 0.95,
    //   prompt: prompt,
    //   temperature: 0.7,
    //   system_prompt: "You are a helpful assistant",
    //   system_prompt: "You are an expert analyst tasked with identifying the main idea of a website based on provided texts. Summarize the core theme concisely in 100 words.",
    //   length_penalty: 1,
    //   max_new_tokens: 512,
    //   stop_sequences: "<|end_of_text|>,<|eot_id|>",
    //   prompt_template:
    //     "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n",
    //   presence_penalty: 0,
    // },

    // 3
    // const model =
    //   "nateraw/nous-hermes-llama2-awq:b3f3f0120a3c4fd37a5e75164cc3ed883c248b9e6d004a70f0d31c3b0debb604";
    // input: {
    //   top_k: 50,
    //   top_p: 0.95,
    //   prompt: "give me a 🔥 weeknight recipe for a Japanese curry",
    //   temperature: 0.8,
    //   max_new_tokens: 512,
    //   prompt_template: "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{prompt}\n\n### Response:\n",
    //   presence_penalty: 0,
    //   frequency_penalty: 0
    // }
    // const prompt_template =
    //   "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nAnalyze the following texts extracted from a website and determine the main idea of the website. Provide a concise summary in approximately 100 words.\n\n### Texts:\n{prompt}\n\n### Response:\n";

    console.log("Running the model " + model);
    const prompt = `I find these texts from a website. what is the main idea of the website? just say the main idea, summarize and in 100 words.  \n\n ${text12}`;

    const output = await replicate.run(model, {
      input: {
        top_p: 0.95,
        prompt: prompt,
        temperature: 0.7,
        system_prompt:
          "You are an expert analyst tasked with identifying the main idea of a website based on provided texts. Summarize the core theme concisely in 100 words.",
        length_penalty: 1,
        max_new_tokens: 512,
        stop_sequences: "<|end_of_text|>,<|eot_id|>",
        prompt_template:
          "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n",
        presence_penalty: 0,
      },
    });
    console.log("finish the model...");

    console.log(output.join(" "));
    console.log("end the model...");
  } catch (error) {
    console.log(error);
  }
}
name();
